# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title:
- content:
bottom_saying: Thank You for Following.
# Content
excerpt_link: Read More

# rss: /atom.xml

highlightjs: arta

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/AlisonChenab
# twitter: https://twitter.com/
# facebook: https://www.facebook.com/
# google: https://google.com/
# weibo: http://weibo.com/

#About timeline
timeline:
- num: 1
  date: 2014/06/12
  content: Start
- num: 2
  date: 2014/06/12
  content: Start
- num: 3
  date: 2014/06/12
  content: Start
- num: 4
  date: 2014/06/12
  content: Start

#Works
# works:
# - works_name: AAA
#   works_url: /
# - works_name: BBB
#   works_url: /atom.xml

#Links
# links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
